trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'TestsX86'
  strategy:
    matrix:
      Python39Mac:
        imageName: "macos-latest"
        python.version: '3.9'
      Python311Mac:
        imageName: "macos-latest"
        python.version: '3.11.0-rc.2'
  pool:
      vmImage: $(imageName)
  steps:
  - template: .github/azure-steps.yml
    parameters:
      python_version: '$(python.version)'
      architecture: 'x64'
